---
- name: Remove nginx, update cache
  hosts: all
  become: true
  tasks:
    - name: update cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Remove nginx
      ansible.builtin.apt:
        apt: nginx
        state: absent