---
- name: Install nginx, update cache
  hosts: all
  become: true
  tasks:
    - name: update cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Install nginx
      ansible.builtin.apt:
        name: nginx
        state: present
        update_cache: yes
      notify: restart_nginx

handlers:
  - name: restart_nginx
    service:
      name: nginx
      state: restarted